version: '3.7'

networks:
  prometheus-network:

services:
  prometheus:
    image: prom/prometheus:v2.36.2
    user: "0:0"
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - ./data/prometheus:/prometheus
      - ./config/file_sd:/file_sd
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - prometheus-network
    restart: always

  grafana:
    image: grafana/grafana:9.0.2
    user: "0:0"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    env_file:
      - ./config/grafana/.env
    networks:
      - prometheus-network
    restart: always