networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./config:/etc/loki/config
      - ./loki/index:/opt/loki/index
      - ./loki/chunks:/opt/loki/chunks
    networks:
      - loki
    user: "0:0"
    command: -config.file=/etc/loki/config/loki-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./config:/etc/promtail/config
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - loki
    command: -config.file=/etc/promtail/config/promtail-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 9266:3000
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - loki
    user: "0:0"
    restart: unless-stopped
