version: "3.9"

services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.4.0
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    network_mode: "host"
    restart: unless-stopped
    privileged: true
